services:
  # Comment on the entire database service
  db:
    image: postgres:17.10
    container_name: anylistdb
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  anylistapp:
    # Comment depends_on
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    # image: nest-graphql-app
    iamge: adriayc/nest-graphql-app
    container_name: AnyListApp
    restart: always # Reiniciar el contenedor si se detiene
    ports:
      - '${PORT}:${PORT}'
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=${PORT}
      - NEST_ENV=${NEST_ENV}
      - JWT_SECRET=${JWT_SECRET}
